# initialize an array x X y dimension with 0

In [17]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# arranging nos btwn x & y with interval of z

In [18]:
import numpy as np
np.arange(10,75,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

# 1 dimensional array

In [1]:
import numpy as np
b = np.array([1,2,3])
print(b)

[1 2 3]


# 2 dimensional array

In [2]:
import numpy as np
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# initialize all elements of x X y array to 0

In [9]:
import numpy as np
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# arrange z nos btwn x & y

In [5]:
import numpy as np
np.linspace(5,10,6)   #inclusive

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [6]:
 import numpy as np
np.linspace(2,8,4)

array([2., 4., 6., 8.])

# filling same nos in an array of dimension x X y

In [12]:
import numpy as np
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [13]:
import numpy as np
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

# filling RANDOM nos in an array of x X y

In [14]:
import numpy as np
np.random.random((2,2))

array([[0.05602177, 0.55514027],
       [0.1693022 , 0.74177474]])

In [15]:
import numpy as np
np.random.random((1,7))

array([[0.62771762, 0.10789184, 0.81353606, 0.52539361, 0.87389164,
        0.55320323, 0.7179187 ]])

In [16]:
import numpy as np
np.random.random((3,3))

array([[0.64143912, 0.34680802, 0.36758157],
       [0.92034516, 0.97700315, 0.35549258],
       [0.26069286, 0.66341401, 0.01864415]])