# addition using numpy

In [1]:
#type 1
import numpy as np
np.sum([10,20])

30

In [3]:
#type 2
a,b = 10,20
np.sum([a,b])

30

In [4]:
#type 3
np.sum([[1,2],[3,1]], axis=0)  #axis=0 rowwise

array([4, 3])

In [5]:
#type 4
np.sum([[3,3],[6,6]], axis=1)

array([ 6, 12])

In [2]:
#type 5
np.sum([[3,3,9],[6,6,2]], axis=1)

array([15, 14])

# subtraction using numpy

In [4]:
np.subtract(10,20)

-10

# other maths fns using numpy

In [5]:
np.multiply(2,3) #multiply

6

In [6]:
np.divide(10,5)  #divide

2.0

In [7]:
a = np.array([2,3,4]) #multiply arrays
b = np.array([5,6,3])
np.multiply(a,b)

array([10, 18, 12])

In [8]:
#exp, sqrt, sin, cos, log
import numpy as np
a=[1,2,4]
print("xyz",np.exp(a))
print("square root :", np.sqrt(a))
print("sine :", np.sin(a))
print("cos :", np.cos(a))
print("tan :", np.sin(a))
print("log :", np.sin(a))

xyz [ 2.71828183  7.3890561  54.59815003]
square root : [1.         1.41421356 2.        ]
sine : [ 0.84147098  0.90929743 -0.7568025 ]
cos : [ 0.54030231 -0.41614684 -0.65364362]
tan : [ 0.84147098  0.90929743 -0.7568025 ]
log : [ 0.84147098  0.90929743 -0.7568025 ]


# array comparison

In [11]:
#element wise comparison
a = [1,2,3]
b = [3,2,3]
c = [1,2,3]
np.equal(a,b)

array([False,  True,  True])

In [12]:
#array wise comparison
a = [1,2,3]
b = [1,2,3]
c = [1,2,4]
print(np.array_equal(a,c))
np.array_equal(a,b)

False


True

# aggregate functions

In [22]:
import numpy as np
a=[1,2,4]
b=[2,4,4]
c=[1,2,4]
print(np.sum(a)) #array wise sun
print(np.min(a)) #min of an array
print(np.mean(a)) 
print(np.median(a))
print(np.corrcoef(a))
print(np.std(a))

7
1
2.3333333333333335
2.0
1.0
1.247219128924647


# broadcasting
#used when we have 2 arrays of different dimension each but with same no of rows and columns

In [13]:
import numpy as np
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([0,1,2])

print('First array: \n',a,'\n')
print('Second array: \n',b,'\n')

print('total of 1st and 2nd : \n\n',a+b)

First array: 
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Second array: 
 [0 1 2] 

total of 1st and 2nd : 

 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
