# inspecting an array - check the size of an array

In [1]:
import numpy as np
a = np.array([[2,3,4],[5,6,7]])
print(a.shape)

(2, 3)


# inspecting an array - resize an array

In [3]:
a = np.array([[2,3,4],[4,5,6]])
a.shape=(3,2)
print(a)

[[2 3]
 [4 4]
 [5 6]]
2



# return dimension of an array

In [4]:
a = np.arange(24)
print(a.ndim)

1


In [7]:
a = np.array([[2,3,4],[4,5,6]])
a.shape=(3,2,1)
print(a)
print(a.ndim)

[[[2]
  [3]]

 [[4]
  [4]]

 [[5]
  [6]]]
3


In [8]:
a = np.arange(24)
a
b = a.reshape(2,3,4) #trick is to calc the factors of 24: 1,2,3,4,6,12,24
print(b.ndim)

3


# find no of elements in an array

In [9]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d.size) #returns no of elements

9


In [9]:
d = np.array([[1,2,3],[4,5,6],[7,8,9,1]])
print(d.size) # returns only number of rows


3


<ipython-input-9-7e0cf2440894>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d = np.array([[1,2,3],[4,5,6],[7,8,9,1]])


# finding data type of an array

In [12]:
a = np.arange(24)
print(a.dtype)
a

int32


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
a = np.arange(24, dtype = float)
print(a.dtype)
a

float64


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [17]:
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
d.dtype

dtype('int32')

In [19]:
f = np.array([[1,2.9,3],[4,5.7,6],[7,8,9]])
f.dtype

dtype('float64')