# Array Manipulation

# # concatenate 2 arrays

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [2]:
#stack array row-wise: vertically
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# stack array row-wise : horizontally
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [5]:
#combining col-wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

vstack,hstack and column_stack (3 VHS)

# Splitting Array

In [4]:
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
#split the same array horiz - after 2 cols
import numpy as np
x = np.arange(16).reshape(4,4)
print(x, "\n\n")
print(np.hsplit(x,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [12]:
#split the same array horiz - after 3 cols
x = np.arange(16).reshape(4,4)
print(x, "\n\n")
print(np.hsplit(x,2))
print("\n\n", np.hsplit(x,np.array([3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [20]:
# to split 2 cols in 2 groups - 1&2 in one array and 3&4 in 2nd array
x = np.arange(16).reshape(4,4)
print(x, "\n\n")
print(np.hsplit(x,2))
print("\n\n", np.hsplit(x,np.array([2,3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([], shape=(4, 0), dtype=int32), array([[ 3],
       [ 7],
       [11],
       [15]])]


# Indexing & Slicing

In [14]:
a = ['n','o','p','e','t','o','h','i','m']
a[0:5]

['n', 'o', 'p', 'e', 't']

In [21]:
# to slice arrays based on arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]

array([1, 2, 3])

In [22]:
# to extract 1st array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a[:1]

array([[1, 2, 3]])

In [21]:
# to extract, 2nd and 3rd element from 1st array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a[:1,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3]])

In [24]:
#to extract only 2,3,5 and 6 from the arrays, i.e.,1st 2 rows (horiz) and after 1st col(vertically)
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [25]:
#to extract 5,6,8 and 9 from the array
a[1:,1:]

array([[5, 6],
       [8, 9]])