# Assignment 1

Name : Harsha Singh

1. Import the Numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10

In [2]:
vector_1 = np.zeros(10)
print(vector_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1

In [3]:
vector_1[4]=1
print(vector_1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49

In [4]:
vector_2=np.arange(10,50)
print(vector_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5. Reverse a vector (the first element becomes last)

In [5]:
#Define a vector to be reversed
vector_3=np.arange(11,30)
vector_3

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [6]:
#Reversed vector
np.flip(vector_3)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11])

6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
matrix_1=np.arange(0,9).reshape(3,3)
matrix_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Find indices of non zero elements from [1,2,0,0,4,0] 

In [8]:
array_1=np.array([1,2,0,0,4,0])
array_1

array([1, 2, 0, 0, 4, 0])

In [9]:
non_zero_arr = np.nonzero(array_1)
print(non_zero_arr)

(array([0, 1, 4], dtype=int64),)


1,2,4 are the non zero elements at indices 0,1 and 4 respectively

8. Create a 3x3x3 array with random values

In [10]:
rand_arr = np.random.rand(3,3,3)  #keeps executing random numbers
rand_arr

array([[[0.42735478, 0.03694418, 0.50013514],
        [0.87975273, 0.18505752, 0.40965551],
        [0.31873685, 0.41333614, 0.55802833]],

       [[0.35528024, 0.67643815, 0.28874547],
        [0.9456581 , 0.15372719, 0.49653124],
        [0.29473218, 0.96574629, 0.44056209]],

       [[0.56399979, 0.04835657, 0.05326937],
        [0.67220386, 0.95747589, 0.35768673],
        [0.87088335, 0.86490066, 0.19708022]]])

9. Create a random vector of size 30 and find the mean value

In [11]:
rand_vector = np.random.random(30)
rand_vector

array([0.11065797, 0.26703057, 0.78313954, 0.79923466, 0.42367438,
       0.63216233, 0.85456444, 0.81234023, 0.15545257, 0.49539695,
       0.80584389, 0.9037893 , 0.61409102, 0.00846209, 0.14851383,
       0.22818248, 0.21089961, 0.30867712, 0.28867261, 0.1345064 ,
       0.50022598, 0.32972678, 0.52423944, 0.06157579, 0.90966814,
       0.14066764, 0.2139481 , 0.03199348, 0.40448655, 0.85378154])

In [12]:
rand_vector.mean()

0.431853514308506

Mean will change as random numbers

10. Create a 2d array with 1 on the border and 0 inside

In [13]:
n=int(input("Enter 2D Array dimension :\n"))

Enter 2D Array dimension :
4


In [14]:
two_dim_array = np.ones((n, n), dtype = int)
two_dim_array[1:-1, 1:-1] = 0
print(two_dim_array)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


11. Create an 8x8 matrix and fill it with a checkerboard pattern

In [15]:
check_Board = np.ones((8,8),dtype=int)
check_Board[1::2,::2] = 0
check_Board[::2,1::2] = 0
check_Board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

12.What is the major difference between sets, lists, tuples and dictionaries?

## Solution:
1.List allows duplicate elements
Tuple allows duplicate elements
Set does not allow duplicate elements.
Dictionaries do not allow duplicate elements ie keys cannot be duplicated

2:
Lists are mutable, Tuples are immutable, Sets are mutable and Dictionaries are mutable.

3:
Lists are ordered	Tuples are ordered	Sets are unordered	Dictionaries are ordered

4:
Lists are represented by []	
Tuples are represented by ( )
Sets are represented by { }	
Dictionaries are represented by { }

________________________________________________________________________________________________________________

13. Print first 10 natural numbers using while loop


In [16]:
n=10
i=1
while i<=n:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


14. Print the numbers -10 to -1 using for loop.


In [17]:
for i in range(-10,0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


15.Print the message “Done” after successful execution of any for a loop. 


In [18]:
for i in range(1,6):
    print(i)
print("Done")

1
2
3
4
5
Done


16. Create a random vector of size 10 and sort it

In [19]:
unsorted_vector = np.random.random(10)
unsorted_vector

array([0.52294237, 0.93506609, 0.28062535, 0.87267761, 0.52765258,
       0.77794026, 0.43724195, 0.39214645, 0.34811117, 0.26855081])

In [20]:
unsorted_vector.sort()
print(unsorted_vector)

[0.26855081 0.28062535 0.34811117 0.39214645 0.43724195 0.52294237
 0.52765258 0.77794026 0.87267761 0.93506609]


17. Execute any three math functions using NumPy.

In [21]:
# 1. LEAST COMMON MULTIPLE LCM
np.lcm(np.arange(6), [1,4,9,6,26,24])

array([  0,   4,  18,   6,  52, 120])

LCM(0,1) = 1 LCM(1,4)=4 LCM(2,9)=19, LCM(3,6)=6 LCM (4,10) = 52 LCM (5,24) = 180

In [22]:
# 2. Square Root sqrt
np.sqrt([1,4,6,9,256,999])

array([ 1.        ,  2.        ,  2.44948974,  3.        , 16.        ,
       31.60696126])

In [23]:
# 3 . Power function
x1 = np.array([16, 5, 8, 9, 11, 10])
x2 = np.array([2, 5, 3, 2, 3, 5])
np.power(x1,x2)

array([   256,   3125,    512,     81,   1331, 100000], dtype=int32)

## THE END